<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro [
<!ELEMENT libro ( titulo , autor )>
<!ELEMENT titulo ( #PCDATA )>
<!ELEMENT autor ( nombre , apellido )>
<!ELEMENT nombre ( #PCDATA )>
<!ELEMENT apellido ( #PCDATA)>
 ]>
 
<libro>
<titulo>Titulo1</titulo>
<autor>
  <nombre>Nombre1</nombre>
  <apellido>Apellido1</apellido>
</autor>
</libro>